name = "Albatross"
uuid = "3ca8fdff-dd54-46a1-887c-183655a5fc91"
authors = ["Gabriel B. Santos <gabriel.bertacco@unesp.br>"]
version = "0.0.1-alpha"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNFoil = "5d96e3f7-5e7b-44ae-828e-526bf7f0e78d"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[sources]
NNFoil = {rev = "v0.3.2", url = "https://github.com/gabrielbdsantos/NNFoil.jl"}

[compat]
ConcreteStructs = "0.2.3"
FillArrays = "1.16.0"
LinearAlgebra = "1.11.0"
NNFoil = "0.3.2"
NonlinearSolve = "4.15.0"
julia = "1.11"
