[deps]
Albatross = "3ca8fdff-dd54-46a1-887c-183655a5fc91"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
NNFoil = "5d96e3f7-5e7b-44ae-828e-526bf7f0e78d"

[sources]
Albatross = {path = "../"}
NNFoil = {rev = "v0.3.3", url = "https://github.com/gabrielbdsantos/NNFoil.jl"}
